apiVersion: v1
kind: Service
metadata:
  name: proxy-svc
spec:
  type: NodePort
  selector:
    app: proxy
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30000